### ISSUE TITLE
Code review of AirportsApiSpringboot

### ISSUE THREAD

**Issue by mandyWW** [jefferyforbes/Airports-Api-Springboot#1]
Controller code really well laid out & clear to read, well done. Also, great to see integration tests for each API, excellent work!

Now you need to add in the following:

- server side validation (to check no malicious input can come in) as per: https://reflectoring.io/bean-validation-with-spring-boot/ - we will discuss next week
- database integration (we will discuss/cover this next week)

**Comment by jefferyforbes** [comment]
database integration is completed. I could and maybe will end up coding a custom authentication service for users rather than using basic Auth based on the video I sent
